name: map-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - ipyleaflet
  - requests
  - shapely
  - fiona
  - six
  - pyproj
  - geopandas
  
  
