name: map-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - ipyleaflet
  - requests
  - shapely
  - fiona
  - six
  - pyproj
  - geopandas
  - metpy
  - xarray
  - ftplib
  
